@WeeklyLessonPlanner.Api_HostAddress = http://localhost:5080

GET {{WeeklyLessonPlanner.Api_HostAddress}}/api/system/status
Accept: application/json

###

GET {{WeeklyLessonPlanner.Api_HostAddress}}/api/config
Accept: application/json

###

GET {{WeeklyLessonPlanner.Api_HostAddress}}/api/courses
Accept: application/json

###

GET {{WeeklyLessonPlanner.Api_HostAddress}}/api/calendar
Accept: application/json

###

GET {{WeeklyLessonPlanner.Api_HostAddress}}/api/topics?courseId={{courseId}}
Accept: application/json

###

GET {{WeeklyLessonPlanner.Api_HostAddress}}/api/topic-instances/unplanned?courseId={{courseId}}
Accept: application/json

###

GET {{WeeklyLessonPlanner.Api_HostAddress}}/health/live

###

GET {{WeeklyLessonPlanner.Api_HostAddress}}/health/ready
