// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeeklyLessonPlanner.Infrastructure.Persistence;

#nullable disable

namespace WeeklyLessonPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    [Migration("20260813144709_Phase2CalendarModel")]
    partial class Phase2CalendarModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EventColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExamColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HolidayColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("PlanningEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PlanningStart")
                        .HasColumnType("date");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("VisibleWeekdaysMask")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("app_config", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_config_range", "\"PlanningStart\" <= \"PlanningEnd\"");

                            t.HasCheckConstraint("ck_app_config_singleton", "\"Id\" = 1");

                            t.HasCheckConstraint("ck_app_config_weekdays", "\"VisibleWeekdaysMask\" BETWEEN 1 AND 127");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventColor = "#1565c0",
                            ExamColor = "#ed6c02",
                            HolidayColor = "#2e7d32",
                            PlanningEnd = new DateOnly(2027, 6, 30),
                            PlanningStart = new DateOnly(2026, 9, 1),
                            Version = 0u,
                            VisibleWeekdaysMask = 31
                        });
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.CourseExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("CourseId", "Date")
                        .IsUnique();

                    b.ToTable("course_exams", (string)null);
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.CourseWeekday", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weekday")
                        .HasColumnType("integer");

                    b.HasKey("CourseId", "Weekday");

                    b.ToTable("course_weekdays", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_weekday_value", "\"Weekday\" BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.DatabaseMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("RecordedOn")
                        .HasColumnType("date");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("database_metadata", (string)null);
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.GlobalDayMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("global_day_markers", null, t =>
                        {
                            t.HasCheckConstraint("ck_global_marker_type", "\"Type\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Heading");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.TopicAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("TopicInstanceId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TopicInstanceId")
                        .IsUnique();

                    b.HasIndex("CourseId", "Date")
                        .IsUnique();

                    b.HasIndex("TopicInstanceId", "CourseId")
                        .IsUnique();

                    b.ToTable("topic_assignments", (string)null);
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.TopicInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "CourseId");

                    b.ToTable("topic_instances", (string)null);
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.CourseExam", b =>
                {
                    b.HasOne("WeeklyLessonPlanner.Infrastructure.Persistence.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.CourseWeekday", b =>
                {
                    b.HasOne("WeeklyLessonPlanner.Infrastructure.Persistence.Course", "Course")
                        .WithMany("Weekdays")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.Topic", b =>
                {
                    b.HasOne("WeeklyLessonPlanner.Infrastructure.Persistence.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.TopicAssignment", b =>
                {
                    b.HasOne("WeeklyLessonPlanner.Infrastructure.Persistence.TopicInstance", "TopicInstance")
                        .WithOne("Assignment")
                        .HasForeignKey("WeeklyLessonPlanner.Infrastructure.Persistence.TopicAssignment", "TopicInstanceId", "CourseId")
                        .HasPrincipalKey("WeeklyLessonPlanner.Infrastructure.Persistence.TopicInstance", "Id", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicInstance");
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.TopicInstance", b =>
                {
                    b.HasOne("WeeklyLessonPlanner.Infrastructure.Persistence.Topic", "Topic")
                        .WithMany("Instances")
                        .HasForeignKey("TopicId", "CourseId")
                        .HasPrincipalKey("Id", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.Course", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Topics");

                    b.Navigation("Weekdays");
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.Topic", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("WeeklyLessonPlanner.Infrastructure.Persistence.TopicInstance", b =>
                {
                    b.Navigation("Assignment");
                });
#pragma warning restore 612, 618
        }
    }
}
